{
 "title": "OpenTelemetry Collector",
 "description": "Visualize OpenTelemetry (OTEL) collector metrics (tested with OTEL contrib v0.120.1)",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.*\"})"
    }
   },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "metric", "label": "Base metric", "query": "Rate : rate, Count : increase" },
   {
    "name": "receiver",
    "label": "Receiver",
    "query": {
     "query": "query_result(avg by (receiver) ({__name__=~\"otelcol_receiver_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "processor",
    "label": "Processor",
    "query": {
     "query": "query_result(avg by (processor) ({__name__=~\"otelcol_processor_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "query_result(avg by (exporter) ({__name__=~\"otelcol_exporter_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "grouping",
    "label": "Additional grouping",
    "query": "None (basic metrics) :  , By transport (detailed metrics) : \\,transport, By service instance id : \\,service_instance_id"
   },
   {
    "name": "suffix_total",
    "label": "Suffix _total",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.+\",job=\"$job\"})"
    }
   },
   {
    "name": "suffix_seconds",
    "label": "Suffix _seconds",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.+\",job=\"$job\"})"
    }
   },
   {
    "name": "suffix_bytes",
    "label": "Suffix _bytes",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_memory_rss.+\",job=\"$job\"})"
    }
   },
   {
    "name": "prefix",
    "label": "Prefix",
    "query": {
     "query": "query_result({__name__=~\".*.*rpc_server_duration_bucket|.*rpc_client_duration_bucket|.*http_server_duration_bucket|.*http_client_duration_bucket.*\",job=\"$job\"})"
    }
   },
   { "name": "adhoc", "label": "Ad Hoc" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard uses the metrics generated by the OpenTelemetry Collector.\nIt is used to understand the overall performance and health of the OpenTelemetry Collector.\n<br/>\nChart panels may require 5 minutes after the Demo is started before rendering data.\n"
   }
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the pipeline.\nRefused: count/rate of spans that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_spans${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_spans${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.\nRefused: count/rate of metric points that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_metric_points${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_metric_points${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the pipeline.\nRefused: count/rate of log records that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_log_records${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_log_records${suffix_total}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_incoming_items${suffix_total}{processor=~\"$processor\",job=\"$job\",otel_signal=\"traces\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Incoming: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "0-sum(${metric:value}(otelcol_processor_outgoing_items${suffix_total}{processor=~\"$processor\",job=\"$job\",otel_signal=\"traces\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Outgoing: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_incoming_items${suffix_total}{processor=~\"$processor\",job=\"$job\",otel_signal=\"metrics\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Incoming: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "0-sum(${metric:value}(otelcol_processor_outgoing_items${suffix_total}{processor=~\"$processor\",job=\"$job\",otel_signal=\"metrics\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Outgoing: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Logs Records ${metric:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_incoming_items${suffix_total}{processor=~\"$processor\",job=\"$job\",otel_signal=\"logs\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Incoming: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "0-sum(${metric:value}(otelcol_processor_outgoing_items${suffix_total}{processor=~\"$processor\",job=\"$job\",otel_signal=\"logs\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Outgoing: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Accepted Spans ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the next component in the pipeline.\nRefused: count/rate of spans that were rejected by the next component in the pipeline.\nDropped: count/rate of spans that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_accepted_spans${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Accepted: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_refused_spans${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Refused: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_dropped_spans${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Dropped: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Accepted Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the next component in the pipeline.\nRefused: count/rate of metric points that were rejected by the next component in the pipeline.\nDropped: count/rate of metric points that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_accepted_metric_points${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Accepted: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_refused_metric_points${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Refused: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_dropped_metric_points${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Dropped: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Accepted Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the next component in the pipeline.\nRefused: count/rate of log records that were rejected by the next component in the pipeline.\nDropped: count/rate of log records that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_accepted_log_records${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Accepted: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_refused_log_records${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Refused: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_dropped_log_records${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Dropped: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Batch Send Size Heatmap",
   "type": "heatmap",
   "description": "Number of units in the batch",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(otelcol_processor_batch_batch_send_size_bucket{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batch Metrics 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_count{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch send size count: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_sum{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch send size sum: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Batch Metrics 2",
   "type": "timeseries",
   "description": "Number of times the batch was sent due to a size trigger. Number of times the batch was sent due to a timeout trigger.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_size_trigger_send${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch sent due to a size trigger: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_timeout_trigger_send${suffix_total}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch sent due to a timeout trigger: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of spans successfully sent to destination.\nEnqueue: count/rate of spans failed to be added to the sending queue.\nFailed: count/rate of spans in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_spans${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_spans${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_spans${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEnqueue: count/rate of metric points failed to be added to the sending queue.\nFailed: count/rate of metric points in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_metric_points${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_metric_points${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_metric_points${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of log records successfully sent to destination.\nEnqueue: count/rate of log records failed to be added to the sending queue.\nFailed: count/rate of log records in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_log_records${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_log_records${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_log_records${suffix_total}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "timeseries",
   "description": "Current size of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size{exporter=~\"$exporter\",job=\"$job\"}) by (exporter $grouping)",
     "legendFormat": "Max queue size: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Capacity",
   "type": "timeseries",
   "description": "Fixed capacity of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(otelcol_exporter_queue_capacity{exporter=~\"$exporter\",job=\"$job\"}) by (exporter $grouping)",
     "legendFormat": "Queue capacity: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n    otelcol_exporter_queue_size{\r\n        exporter=~\"$exporter\", job=\"$job\"\r\n    }\r\n) by (exporter $grouping)\r\n/\r\nmin(\r\n    otelcol_exporter_queue_capacity{\r\n        exporter=~\"$exporter\", job=\"$job\"\r\n    }\r\n) by (exporter $grouping)",
     "legendFormat": "Queue capacity usage: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total RSS Memory",
   "type": "timeseries",
   "description": "Total physical memory (resident set size)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_memory_rss${suffix_bytes}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_memory_rss${suffix_bytes}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_memory_rss${suffix_bytes}{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Sys Memory",
   "type": "timeseries",
   "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Heap Memory",
   "type": "timeseries",
   "description": "Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu_seconds${suffix_total}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Max CPU usage {{service_instance_id}}"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds${suffix_total}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Avg CPU usage {{service_instance_id}}"
    },
    {
     "expr": "min(rate(otelcol_process_cpu_seconds${suffix_total}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Min CPU usage {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "description": "Number of service instances, which are reporting metrics",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds${suffix_total}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id))",
     "legendFormat": "Service instance count"
    }
   ]
  },
  {
   "title": "Uptime by Service Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(otelcol_process_uptime${suffix_seconds}${suffix_total}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id)",
     "legendFormat": "Service instance uptime: {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(otelcol_process_uptime${suffix_seconds}${suffix_total}{service_instance_id=~\".*\",job=\"$job\",service_version=\".+\"}) by (service_instance_id,service_name,service_version)\r\nor\r\nmax(\r\n  otelcol_process_uptime${suffix_seconds}${suffix_total}{service_instance_id=~\".*\",job=\"$job\"} \r\n  * on(job, instance) \r\n  group_left(service_version) \r\n  (\r\n    target_info \r\n    * on(job, instance) \r\n    group_left \r\n    label_replace(target_info{}, \"service_instance_id\", \"$1\", \"instance\", \"(.*)\")\r\n  )\r\n) by (service_instance_id, service_name, service_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Signal flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Spans Flow",
   "type": "nodeGraph",
   "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_receiver_accepted_spans${suffix_total}{job=\"$job\"}[$__rate_interval])\n      ) by (receiver)\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime${suffix_seconds}${suffix_total}{job=\"$job\"}[$__rate_interval])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_exporter_sent_spans${suffix_total}{job=\"$job\"}[$__rate_interval])\n      ) by (exporter)\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_spans${suffix_total}{job=\"$job\"}[$__rate_interval])) by (receiver))\r\n            ,\"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        ,\"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_spans${suffix_total}{job=\"$job\"}[$__rate_interval])) by (exporter))\r\n            , \"target\", \"-exp-\", \"transport\", \"exporter\"\r\n        )\r\n        , \"source\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Points Flow",
   "type": "nodeGraph",
   "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 80 },
   "targets": [
    {
     "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      (sum(\n        ${metric:value}(otelcol_receiver_accepted_metric_points${suffix_total}{job=\"$job\"}[$__rate_interval])\n      ) by (receiver))\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime${suffix_seconds}${suffix_total}{job=\"$job\"}[$__rate_interval])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      (sum(\n        ${metric:value}(otelcol_exporter_sent_metric_points${suffix_total}{job=\"$job\"}[$__rate_interval])\n      ) by (exporter))\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_metric_points${suffix_total}{job=\"$job\"}[$__rate_interval])) by (receiver))\r\n            , \"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        , \"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor \r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_metric_points${suffix_total}{job=\"$job\"}[$__rate_interval])) by (exporter))\r\n            , \"target\", \"-exp-\", \"transport\", \"exporter\"\r\n        )\r\n        , \"source\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Records Flow",
   "type": "nodeGraph",
   "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 80 },
   "targets": [
    {
     "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_receiver_accepted_log_records${suffix_total}{job=\"$job\"}[$__rate_interval])\n      ) by (receiver)\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime${suffix_seconds}${suffix_total}{job=\"$job\"}[$__rate_interval])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_exporter_sent_log_records${suffix_total}{job=\"$job\"}[$__rate_interval])\n      ) by (exporter)\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_log_records${suffix_total}{job=\"$job\"}[$__rate_interval])) by (receiver))\r\n            , \"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        , \"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-edg-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor \r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_log_records${suffix_total}{job=\"$job\"}[$__rate_interval])) by (exporter))\r\n            ,\"target\",\"-exp-\",\"transport\",\"exporter\"\r\n        )\r\n        ,\"source\",\"processor\",\"\",\"\"\r\n    )\r\n    ,\"id\",\"-edg-\",\"source\",\"target\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filter processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans ${metric:text}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(${metric:value}(otelcol_processor_filter_spans_filtered${suffix_total}{job=\"$job\"}[$__rate_interval])) by (filter $grouping)",
       "legendFormat": "Filtered: {{filter}} {{transport}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Metric Points ${metric:text}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(${metric:value}(otelcol_processor_filter_datapoints_filtered${suffix_total}{job=\"$job\"}[$__rate_interval])) by (filter $grouping)",
       "legendFormat": "Filtered: {{filter}} {{transport}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Log Records ${metric:text}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(${metric:value}(otelcol_processor_filter_log_records_filtered${suffix_total}{job=\"$job\"}[$__rate_interval])) by (filter $grouping)",
       "legendFormat": "Filtered: {{filter}} {{transport}} {{service_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC server/client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC server responses by GRPC status code (receivers)",
     "type": "timeseries",
     "description": "Measures the number of messages received per RPC. Should be 1 for all non-streaming RPCs. GRPC status codes: https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 291 },
     "targets": [
      {
       "expr": "sum by(rpc_grpc_status_code) (${metric:value}(${prefix:raw}rpc_server_responses_per_rpc_count{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC client responses by GRPC status code (exporters)",
     "type": "timeseries",
     "description": "Measures the number of messages received per RPC. Should be 1 for all non-streaming RPCs. GRPC status codes: https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 291 },
     "targets": [
      {
       "expr": "sum by(rpc_grpc_status_code) (${metric:value}(${prefix:raw}rpc_client_responses_per_rpc_count{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC server duration (receivers)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 300 },
     "targets": [
      {
       "expr": "sum(increase(${prefix:raw}rpc_server_duration_bucket{job=\"$job\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RPC client duration (exporters)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 300 },
     "targets": [
      {
       "expr": "sum(increase(${prefix:raw}rpc_client_duration_bucket{job=\"$job\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RPC server request size (receivers)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 308 },
     "targets": [
      {
       "expr": "sum(increase(${prefix:raw}rpc_server_request_size_bucket{job=\"$job\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RPC client request size (exporters)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 308 },
     "targets": [
      {
       "expr": "sum(increase(${prefix:raw}rpc_client_request_size_bucket{job=\"$job\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP server/client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP server duration (receivers)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 350 },
     "targets": [
      {
       "expr": "sum(increase(${prefix:raw}http_server_duration_bucket{job=\"$job\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP client duration (exporters)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 350 },
     "targets": [
      {
       "expr": "sum(increase(${prefix:raw}http_client_duration_bucket{job=\"$job\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespaces",
     "type": "timeseries",
     "description": "Added: Number of namespace add events received.\nUpdated: Number of namespace update events received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(otelcol_otelsvc_k8s_namespace_added${suffix_total}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Added: {{transport}} {{service_instance_id}}"
      },
      {
       "expr": "avg(otelcol_otelsvc_k8s_namespace_updated${suffix_total}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Updated: {{transport}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "description": "Added: Number of pod add events received.\nUpdated: Number of pod update events received.\nDeleted: Number of pod delete events received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_added${suffix_total}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Added: {{transport}} {{service_instance_id}}"
      },
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_updated${suffix_total}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Updated: {{transport}} {{service_instance_id}}"
      },
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_deleted${suffix_total}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Deleted: {{transport}} {{service_instance_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } }
 ]
}